# Generated by Django 5.2.10 on 2026-01-12 12:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('executando', 'Em Execução'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('parada', 'Parada/Cancelada')], default='aberta', max_length=20)),
                ('duracao_estimada', models.DurationField(help_text='Tempo previsto (Ex: 02:00:00 para 2h)')),
                ('data_planejada', models.DateTimeField(default=django.utils.timezone.now)),
                ('tempo_total_gasto', models.DurationField(default=datetime.timedelta(0))),
                ('ultima_interacao', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maquina')),
            ],
        ),
        migrations.DeleteModel(
            name='Ativo',
        ),
        migrations.DeleteModel(
            name='Localizacao',
        ),
    ]
