# Generated by Django 5.2.10 on 2026-01-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_maquina_atividade_delete_ativo_delete_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código da Preventiva')),
                ('nome', models.CharField(max_length=200)),
                ('instrucoes', models.TextField(blank=True, help_text='Passo a passo técnico')),
                ('duracao_estimada_padrao', models.DurationField(help_text='Tempo padrão para esta tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='eh_preventiva',
            field=models.BooleanField(default=False, verbose_name='É uma manutenção preventiva?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='procedimento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.procedimentopreventivo', verbose_name='Procedimento de Origem'),
        ),
    ]
