# Generated by Django 5.2.10 on 2026-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_procedimentopreventivo_atividade_eh_preventiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='eh_emergencial',
            field=models.BooleanField(default=False, verbose_name='Emergencial (Corta fila)'),
        ),
    ]
