# Generated by Django 5.2.10 on 2026-01-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_atividade_eh_emergencial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('prioridade_indicada', models.IntegerField(choices=[(1, 'Baixa - Pode aguardar'), (2, 'Média - Monitorar'), (3, 'Alta - Urgente')], default=1)),
                ('maquina_parada', models.BooleanField(default=False)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente (Triagem)'), ('aprovado', 'Aprovado (Virou OS)'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maquina')),
                ('requisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
