# Generated by Django 5.2.10 on 2026-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='instrucoes_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='motivo_resposta',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa/Resposta'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('executando', 'Em Execução'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada'), ('parada', 'Parada/Cancelada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
