# Generated by Django 5.2.10 on 2026-01-19 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_atividade_instrucoes_tecnicas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='atividade',
            name='colaboradores',
            field=models.ManyToManyField(related_name='atividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='motivo_pausa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AtividadeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_novo', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.atividade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Lubrificação Semanal', max_length=100)),
                ('frequencia_dias', models.IntegerField(help_text='A cada quantos dias deve ocorrer?')),
                ('proxima_data', models.DateField(help_text='Data da próxima geração automática')),
                ('ativo', models.BooleanField(default=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.maquina')),
                ('procedimento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.procedimentopreventivo')),
            ],
        ),
        migrations.AddField(
            model_name='procedimentopreventivo',
            name='plano_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.planopreventivo'),
        ),
    ]
