# Generated by Django 6.0.1 on 2026-01-25 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_atividade_colaborador_atividade_colaboradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='tempo_total_pausa',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='atividadelog',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
